"""adaptive test attempts

Revision ID: 5ebc8ce7a7a2
Revises: 46235ef5791d
Create Date: 2026-09-08 19:29:54.077906
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5ebc8ce7a7a2'
down_revision: Union[str, None] = '46235ef5791d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_attempts', sa.Column('mode', sa.String(length=16), nullable=False, server_default='fixed'))
    op.add_column('test_attempts', sa.Column('status', sa.String(length=16), nullable=False, server_default='completed'))
    op.create_index(op.f('ix_test_attempts_status'), 'test_attempts', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_attempts_status'), table_name='test_attempts')
    op.drop_column('test_attempts', 'status')
    op.drop_column('test_attempts', 'mode')
    # ### end Alembic commands ###
